name: Build OverTone Executable

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install

      - name: Bundle react
        run: npm run build

      - name: Bundle electron
        run: npm run make

      - name: Isolate files
        shell: bash
        run: |
          mkdir -p release

          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            cp dist/*.zip release/
            cp dist/*.exe release/
          fi

          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            file=$(find . -maxdepth 1 -name "dist/*.zip" -type f | head -n 1)
            cp "$file" "${file%.zip}-linux.zip"
            cp dist/*.AppImage release/
          fi

          if [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            cp dist/*.zip release/
            cp dist/*.dmg release/
          fi

      - name: Upload to artifacts
        uses: actions/upload-artifact@v6
        with:
          name: ${{ matrix.os }}
          path: release/**
        
      - name: Upload to Release
        if: ${{ github.event_name == 'release' }}
        uses: softprops/action-gh-release@v1
        with:
          files: release/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}