name: Build OverTone Executable

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        # os: [windows-latest, macos-latest]
        os: [ubuntu-latest]
        # os: [windows-latest, macos-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Bundle react
        run: npm run build

      - name: Bundle electron
        run: npm run make

      - name: Isolate files
        shell: bash
        run: |
          mkdir -p release

          # if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
          #   cp out/make/zip/linux/x64/*.zip release/
          # fi

          if [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            cp out/make/*.dmg release/
            cp out/make/zip/darwin/arm64/*.zip release/
          fi

          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            cp out/make/zip/win32/x64/*.zip release/
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}
          path: out/make/**
          # path: release/**
          
      - name: Upload to Release
        if: ${{ github.event_name == 'release' }}
        uses: softprops/action-gh-release@v1
        with:
          files: release/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}